server:
  port: 3334
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: caas-common-api
  security:
    username: admin
    password: PaaS-TA
  datasource:
    url: jdbc:mysql://[db_server]:[db_port]/caas?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: 'user'
    password: 'password'
    validationQuery: SELECT 1
    driver_class_name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.EJB3NamingStrategy
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

caasApi:
  url: http://localhost:3333
  authorization:
    id: admin
    password: PaaS-TA